# Generated by Django 3.2.12 on 2022-04-18 06:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(related_name='follwers', to=settings.AUTH_USER_MODEL),
        ),
    ]
